#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


require 'search_query_parser/grammar'

class SearchQueryParser::ParseError < ArgumentError; end

module SearchQueryParser
  class Interpreter < Racc::Parser

module_eval(<<'...end interpreter.y/module_eval...', 'interpreter.y', 24)

  def parse(str)
    @q = []
    str.scan(/[[:alnum:]\-]+|[&|()\s]/) do |token|
      case token
      when /[[:alnum:]\-]+/
        @q.push [:TERM, SearchQueryParser::Grammar.new(token)]
      when /\s/
        @q.push ['<->', '<->']
      else
        @q.push [token, token]
      end
    end
    @q.push [false, '$end']
    begin
      do_parse
    rescue Racc::ParseError => e
      raise SearchQueryParser::ParseError.new(e)
    end
  end

  def next_token
    @q.shift
  end

...end interpreter.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     8,     6,     7,    10,    14,     8,     6,     7,     3,     3,
     4,     4,     3,     3,     4,     4,     3,     5,     4,     8,
     6,     8 ]

racc_action_check = [
     9,     9,     9,     5,     9,     2,     2,     2,     3,     0,
     3,     0,     6,     7,     6,     7,     8,     1,     8,    12,
    12,    11 ]

racc_action_pointer = [
     4,    17,     3,     3,   nil,     3,     7,     8,    11,    -2,
   nil,    19,    17,   nil,   nil ]

racc_action_default = [
    -7,    -7,    -1,    -7,    -6,    -7,    -7,    -7,    -7,    -7,
    15,    -2,    -3,    -4,    -5 ]

racc_goto_table = [
     2,     1,   nil,     9,   nil,   nil,    11,    12,    13 ]

racc_goto_check = [
     2,     1,   nil,     2,   nil,   nil,     2,     2,     2 ]

racc_goto_pointer = [
   nil,     1,     0 ]

racc_goto_default = [
   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 9, :_reduce_none,
  3, 10, :_reduce_2,
  3, 10, :_reduce_3,
  3, 10, :_reduce_4,
  3, 10, :_reduce_5,
  1, 10, :_reduce_6 ]

racc_reduce_n = 7

racc_shift_n = 15

racc_token_table = {
  false => 0,
  :error => 1,
  "<->" => 2,
  "&" => 3,
  "|" => 4,
  "(" => 5,
  ")" => 6,
  :TERM => 7 }

racc_nt_base = 8

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"<->\"",
  "\"&\"",
  "\"|\"",
  "\"(\"",
  "\")\"",
  "TERM",
  "$start",
  "target",
  "exp" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'interpreter.y', 9)
  def _reduce_2(val, _values, result)
     result &= val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'interpreter.y', 10)
  def _reduce_3(val, _values, result)
     result |= val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'interpreter.y', 11)
  def _reduce_4(val, _values, result)
     result >>= val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'interpreter.y', 12)
  def _reduce_5(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'interpreter.y', 13)
  def _reduce_6(val, _values, result)
     result = val[0] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Interpreter
  end   # module SearchQueryParser


